#!/usr/bin/env bash
# Generate Codex-format subagent definitions from the portable reviewer roles.
#
# The canonical reviewer-role prompts live in `.claude/agents/*.md` (YAML
# frontmatter + a markdown body). Codex's multi-agent feature (`spawn_agent`)
# discovers project subagents from `.codex/agents/*.toml` — a different format
# and schema. This script projects the `.claude/agents/` source of truth into
# that Codex format so `$review` can dispatch the same roles through Codex's
# native subagents. `.claude/agents/` stays the single source; the generated
# `.codex/agents/` TOMLs are a build product kept in sync by this script.
#
# Usage:
#   scripts/sync-codex-agents.sh            # (re)generate .codex/agents/*.toml
#   scripts/sync-codex-agents.sh --check    # verify committed files are in sync
#                                           # (exit 1 on drift; mutates nothing)
#
# The --check mode is the CI/harness gate: regenerate into a temp dir and diff
# against the committed tree, mirroring scripts/check-planning-clean.sh.
set -euo pipefail

repo_root() { git rev-parse --show-toplevel 2>/dev/null || { cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd; }; }
ROOT="$(repo_root)"
SRC_DIR="$ROOT/.claude/agents"
GENERATED_HEADER="# GENERATED by scripts/sync-codex-agents.sh from .claude/agents/%s.md — do not edit."

# Emit one Codex agent TOML for a single .claude/agents/<name>.md to stdout.
render_agent() {
  local src="$1" name frontmatter body description
  name="$(basename "$src" .md)"

  # Only the first two `---` lines are frontmatter delimiters; the `c<2` guard
  # stops counting after them, so a `---` thematic break inside the body is
  # treated as content and passes through instead of being swallowed.
  frontmatter="$(awk 'c<2 && /^---[[:space:]]*$/{c++; next} c==1{print} c>=2{exit}' "$src")"
  # Body is everything after the second `---`, with leading/trailing blank
  # lines trimmed so the embedded prompt starts on its first real line.
  body="$(awk 'c<2 && /^---[[:space:]]*$/{c++; next} c>=2{print}' "$src" \
    | sed -e '/./,$!d' | tac | sed -e '/./,$!d' | tac)"

  description="$(printf '%s\n' "$frontmatter" | sed -n 's/^description:[[:space:]]*//p' | head -n1)"

  # Fail loudly rather than emit a structurally-valid-but-broken agent. The
  # name becomes the TOML `name`/`agent_type`, so it must be a safe slug; a
  # missing description or body means the frontmatter did not parse (e.g. fewer
  # than two `---` delimiters); and a `"`/`\` in the basic-string description or
  # a `'''` in the literal-string body would escape its TOML string.
  if ! printf '%s' "$name" | grep -qE '^[a-z][a-z0-9-]*$'; then
    echo "sync-codex-agents: '$name' is not a safe agent name (must match ^[a-z][a-z0-9-]*)" >&2
    return 1
  fi
  if [ -z "$description" ]; then
    echo "sync-codex-agents: $name has no 'description:' frontmatter (or the frontmatter did not parse)" >&2
    return 1
  fi
  if [ -z "$body" ]; then
    echo "sync-codex-agents: $name has an empty body (missing '---' frontmatter delimiters?)" >&2
    return 1
  fi
  if printf '%s' "$description" | grep -q '["\\]'; then
    echo "sync-codex-agents: $name description contains a quote/backslash unsafe for TOML basic string" >&2
    return 1
  fi
  if printf '%s' "$body" | grep -q "'''"; then
    echo "sync-codex-agents: $name body contains ''' which breaks TOML literal string" >&2
    return 1
  fi

  # SC2059: GENERATED_HEADER is a fixed literal with exactly one %s and $name is
  # passed as the argument (never interpolated into the format string), so this
  # is not a format-string injection surface even for an odd filename.
  # shellcheck disable=SC2059
  printf "$GENERATED_HEADER\n" "$name"
  printf 'name = "%s"\n' "$name"
  printf 'description = "%s"\n' "$description"
  # Reviewers are read-only advisors (see .claude/skills/review/SKILL.md host
  # dispatch contract); the sandbox enforces that for spawned Codex agents.
  printf 'sandbox_mode = "read-only"\n'
  printf "developer_instructions = '''\n"
  printf '%s\n' "$body"
  printf "'''\n"
}

generate_into() {
  local dest="$1" staging src name
  mkdir -p "$dest"
  # Render into a staging dir first, then swap into place only after every role
  # rendered successfully. This makes generation atomic: a failed render (bad
  # frontmatter, unsafe name) aborts before `$dest` is touched, so it never
  # leaves a partial tree or a zero-byte file. The prune before the move drops
  # orphan TOMLs whose source `.claude/agents/*.md` was deleted or that were
  # hand-dropped into `.codex/agents/`.
  staging="$(mktemp -d)"
  for src in "$SRC_DIR"/*.md; do
    name="$(basename "$src" .md)"
    render_agent "$src" > "$staging/$name.toml" || { rm -rf "$staging"; return 1; }
  done
  rm -f "$dest"/*.toml
  mv "$staging"/*.toml "$dest"/
  rm -rf "$staging"
}

main() {
  local mode="${1:-generate}"
  case "$mode" in
    --check)
      # tmp is intentionally global: the EXIT trap fires after main() returns,
      # by which point a function-local would be out of scope under `set -u`.
      tmp="$(mktemp -d)"
      trap 'rm -rf "${tmp:-}"' EXIT
      generate_into "$tmp"
      if ! diff -ru "$ROOT/.codex/agents" "$tmp" >/dev/null 2>&1; then
        echo "sync-codex-agents: .codex/agents/ is out of sync with .claude/agents/" >&2
        diff -ru "$ROOT/.codex/agents" "$tmp" >&2 || true
        echo "Run: scripts/sync-codex-agents.sh" >&2
        return 1
      fi
      echo "sync-codex-agents: .codex/agents/ is in sync"
      ;;
    generate|"")
      generate_into "$ROOT/.codex/agents"
      local written=( "$ROOT"/.codex/agents/*.toml )
      echo "sync-codex-agents: wrote ${#written[@]} agent(s) to .codex/agents/"
      ;;
    *)
      echo "usage: $0 [--check]" >&2
      return 2 ;;
  esac
}

main "$@"
