#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# plugin/provisioner/40-path-wiring.sh — six-mode PATH/locale wiring.
#
# Sourced by agentlinux-install. Inherits set -euo pipefail, the ERR trap, and
# the tee redirect — MUST NOT set its own strict-mode flags.
#
# Wires /home/agent/.npm-global/bin onto PATH across all six invocation modes
# (BHV-02 SSH, BHV-03 cron, BHV-04 systemd, BHV-05 sudo -u [-i], BHV-06 login;
# RT-02 PATH, RT-04 NPM_CONFIG_PREFIX) via four artefacts:
#   1. /etc/profile.d/agentlinux.sh  (0644 root:root)  — login + sudo -u -i
#   2. /home/agent/.bashrc TOP block (0644 agent:agent) — SSH + sudo -u bash -c
#   3. /etc/agentlinux.env           (0644 root:root)  — systemd EnvironmentFile
#   4. /etc/cron.d/agentlinux        (0644 root:root)  — cron PATH header
#
# Path ordering: agent-owned prefixes FIRST, system prefixes last — prevents
# path-injection by a wider-writable directory earlier in PATH. Mutations go
# through write_file_atomic (installer-owned files) or ensure_marker_block
# (user-owned ~agent/.bashrc); no raw-append or in-place edit. No wrapper shim
# pointing at an agent-owned binary (the canonical self-update bug). The
# profile.d fragment is written, never executed during install.
#
# NOTE (AL-59): every /home/agent path below is hardcoded — an accepted
# alternate install user (INSTALL_USER != agent) is NOT wired here yet.

# Runs UNCONDITIONALLY for both CREATE and REUSE — the artefacts are additive
# (ensure_marker_block preserves user content outside its block; the three
# root-owned files are installer-owned by contract). PATH wiring is the
# canonical additive Remediate, so no RESOLUTIONS dispatch is needed here.
log_info "40-path-wiring: starting"

# When the user was REUSED, emit the [REMEDIATE-02] marker so the log
# distinguishes re-attaching PATH wiring from creating it (the wiring code is
# identical — the additive primitives converge regardless of prior state).
[[ "${REUSED_USER:-false}" == "true" ]] && remediate::user::log_path_wiring_remediated

# Ensure /home/agent/.local/bin exists so the PATH prefix below isn't a dangling
# reference. ensure_dir re-asserts mode+ownership on re-run.
ensure_dir /home/agent/.local 0755 agent:agent
ensure_dir /home/agent/.local/bin 0755 agent:agent

# Artefact 1: /etc/profile.d/agentlinux.sh — interactive login + `sudo -u -i`.
# Sourced by /etc/profile; the re-source guard prevents a double PATH-prepend.
# write_file_atomic is the portable analogue of `install -m 0644 /dev/stdin
# <dest>` (atomic rename via a same-dir tmpfile), needed because uutils' Rust
# install on Ubuntu 26.04 ENOENTs chasing /dev/stdin when the dest exists. The
# single-quoted heredoc tag keeps $PATH etc. literal in the written file.
write_file_atomic 0644 /etc/profile.d/agentlinux.sh <<'PROFILE'
# AgentLinux login environment (generated by agentlinux-install).
# Sourced by /etc/profile on interactive login shells AND `sudo -u agent -i`.
# Re-source guard: bails on second source in the same shell session so that
# rc reload (e.g. `exec bash -l`) does not double-prepend PATH entries.
[ -n "${AGENTLINUX_PROFILE_SOURCED:-}" ] && return
export AGENTLINUX_PROFILE_SOURCED=1

export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"

# Prepend in order so /home/agent/.npm-global/bin lands FIRST in the final
# PATH (a stray /usr/local/bin shim must lose to the agent-owned binary).
# Case-prepend stacks LIFO: the LAST successful case-block prepends in front
# of everything, so we put .local/bin FIRST and .npm-global/bin SECOND.
# Case-guards prevent double-prepend on re-source (idempotency).
case ":${PATH}:" in
  *:/home/agent/.local/bin:*) : ;;
  *) PATH="/home/agent/.local/bin:${PATH}" ;;
esac
case ":${PATH}:" in
  *:/home/agent/.npm-global/bin:*) : ;;
  *) PATH="/home/agent/.npm-global/bin:${PATH}" ;;
esac
export PATH
PROFILE
log_info "wrote /etc/profile.d/agentlinux.sh"

# Artefact 2: /home/agent/.bashrc marker block at TOP — non-interactive SSH
# (`ssh agent@host 'cmd'`) + `sudo -u agent bash -c 'cmd'`.
# The Ubuntu skel .bashrc early-returns for non-interactive shells
# (`case $- in *i*) ;; *) return;; esac`); --top placement puts our
# guard-source BEFORE that return so those invocations still pick up PATH +
# locale. Create an empty agent-owned file first if .bashrc is absent (minimal
# container with no skel copy) so ensure_marker_block has a target.
if [[ ! -f /home/agent/.bashrc ]]; then
  install -m 0644 -o agent -g agent /dev/null /home/agent/.bashrc
fi
ensure_marker_block /home/agent/.bashrc "agentlinux-path" --top <<'BASHRC'
# AgentLinux PATH guard — sources /etc/profile.d/agentlinux.sh unconditionally
# so non-interactive bash invocations (ssh host 'cmd', sudo -u agent bash -c)
# see the correct PATH + locale BEFORE the skel .bashrc case-return guard.
if [ -f /etc/profile.d/agentlinux.sh ]; then
  . /etc/profile.d/agentlinux.sh
fi
BASHRC
# ensure_marker_block leaves the file root-owned; re-assert agent:agent + 0644
# so the user can edit outside the block.
chown agent:agent /home/agent/.bashrc
chmod 0644 /home/agent/.bashrc
log_info "wrote agentlinux-path marker block to /home/agent/.bashrc (--top)"

# Artefact 3: /etc/agentlinux.env — systemd EnvironmentFile (BHV-04), RT-02 +
# RT-04. FORMAT: literal KEY=VALUE, no `export`, no shell expansion (systemd and
# cron parse this shape literally; `PATH=$PATH:...` would store the literal
# string). NPM_CONFIG_PREFIX is the belt-and-braces fallback so consumers see
# the prefix even if ~agent/.npmrc regresses; keep its value byte-identical to
# the .npmrc prefix line written by 30-nodejs.sh (a cross-grep enforces this).
write_file_atomic 0644 /etc/agentlinux.env <<'ENVFILE'
PATH=/home/agent/.npm-global/bin:/home/agent/.local/bin:/usr/local/bin:/usr/bin:/bin
NPM_CONFIG_PREFIX=/home/agent/.npm-global
LANG=C.UTF-8
LC_ALL=C.UTF-8
ENVFILE
log_info "wrote /etc/agentlinux.env (systemd EnvironmentFile + cron header template)"

# Artefact 4: /etc/cron.d/agentlinux — cron PATH header (BHV-03). The top-of-file
# `PATH=` applies to every job below. No default jobs ship. vixie-cron does NOT
# expand $PATH, so the literal PATH is written fully expanded; keep it
# byte-identical to /etc/agentlinux.env (a cross-grep enforces this).
write_file_atomic 0644 /etc/cron.d/agentlinux <<'CRON'
# AgentLinux cron environment (generated by agentlinux-install).
# Any agent cron job placed in this file inherits the PATH/locale below.
# Phase 2 ships NO default jobs. Example shape (do NOT uncomment):
#   0 3 * * * agent /usr/bin/true

PATH=/home/agent/.npm-global/bin:/home/agent/.local/bin:/usr/local/bin:/usr/bin:/bin
LANG=C.UTF-8
LC_ALL=C.UTF-8
CRON
log_info "wrote /etc/cron.d/agentlinux (PATH + locale header; no default jobs)"

log_info "40-path-wiring: done (four artefacts written)"
