#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# plugin/provisioner/40-path-wiring.sh — six-mode PATH/locale wiring.
#
# Sourced by agentlinux-install. Inherits set -euo pipefail, the ERR trap, and
# the tee redirect — MUST NOT set its own strict-mode flags.
#
# Wires <home>/.npm-global/bin onto PATH across all six invocation modes
# (BHV-02 SSH, BHV-03 cron, BHV-04 systemd, BHV-05 sudo -u [-i], BHV-06 login;
# RT-02 PATH, RT-04 NPM_CONFIG_PREFIX) via four artefacts:
#   1. /etc/profile.d/agentlinux.sh  (0644 root:root)  — login + sudo -u -i
#   2. <home>/.bashrc TOP block      (0644 user:user)  — SSH + sudo -u bash -c
#   3. /etc/agentlinux.env           (0644 root:root)  — systemd EnvironmentFile
#   4. /etc/cron.d/agentlinux        (0644 root:root)  — cron PATH header
#
# Path ordering: user-owned prefixes FIRST, system prefixes last — prevents
# path-injection by a wider-writable directory earlier in PATH. Mutations go
# through write_file_atomic (installer-owned files) or ensure_marker_block
# (user-owned <home>/.bashrc); no raw-append or in-place edit. No wrapper shim
# pointing at a user-owned binary (the canonical self-update bug). The
# profile.d fragment is written, never executed during install.
#
# AL-59 (DONE): every per-user path below derives from the resolved install user
# (_AL_USER / _AL_HOME), so an accepted alternate install user
# (INSTALL_USER != agent) is fully wired here. /etc/agentlinux.env carries
# AGENTLINUX_USER + AGENTLINUX_AGENT_HOME as the runtime source-of-truth the
# catalog CLI reads. The heredocs are UNQUOTED so ${_AL_HOME} interpolates;
# runtime-shell vars ($PATH, ${LANG:-...}, the re-source guard) are escaped (\$)
# so they stay literal in the written file. For the default user `agent` the
# emitted bytes are identical to the pre-AL-59 hardcoded form (cross-grep +
# INST-02 idempotency both still hold).

# Runs UNCONDITIONALLY for both CREATE and REUSE — the artefacts are additive
# (ensure_marker_block preserves user content outside its block; the three
# root-owned files are installer-owned by contract). PATH wiring is the
# canonical additive Remediate, so no RESOLUTIONS dispatch is needed here.
log_info "40-path-wiring: starting"

# Resolved install user + home. The alt-user flow may have updated INSTALL_USER;
# fall back to literal `agent` when unset/empty.
_AL_USER="${INSTALL_USER:-agent}"
_AL_HOME="/home/${_AL_USER}"

# When the user was REUSED, emit the [REMEDIATE-02] marker so the log
# distinguishes re-attaching PATH wiring from creating it (the wiring code is
# identical — the additive primitives converge regardless of prior state).
[[ "${REUSED_USER:-false}" == "true" ]] && remediate::user::log_path_wiring_remediated

# Ensure <home>/.local/bin exists so the PATH prefix below isn't a dangling
# reference. ensure_dir re-asserts mode+ownership on re-run.
ensure_dir "${_AL_HOME}/.local" 0755 "${_AL_USER}:${_AL_USER}"
ensure_dir "${_AL_HOME}/.local/bin" 0755 "${_AL_USER}:${_AL_USER}"

# Artefact 1: /etc/profile.d/agentlinux.sh — interactive login + `sudo -u -i`.
# Sourced by /etc/profile; the re-source guard prevents a double PATH-prepend.
# write_file_atomic is the portable analogue of `install -m 0644 /dev/stdin
# <dest>` (atomic rename via a same-dir tmpfile), needed because uutils' Rust
# install on Ubuntu 26.04 ENOENTs chasing /dev/stdin when the dest exists. The
# heredoc tag is UNQUOTED so ${_AL_HOME}/${_AL_USER} interpolate; the runtime
# shell vars (\$PATH etc.) and backticks are escaped to stay literal.
write_file_atomic 0644 /etc/profile.d/agentlinux.sh <<PROFILE
# AgentLinux login environment (generated by agentlinux-install).
# Sourced by /etc/profile on interactive login shells AND \`sudo -u ${_AL_USER} -i\`.
# Re-source guard: bails on second source in the same shell session so that
# rc reload (e.g. \`exec bash -l\`) does not double-prepend PATH entries.
[ -n "\${AGENTLINUX_PROFILE_SOURCED:-}" ] && return
export AGENTLINUX_PROFILE_SOURCED=1

export LANG="\${LANG:-C.UTF-8}"
export LC_ALL="\${LC_ALL:-C.UTF-8}"
# Keep the Antigravity CLI's catalog-managed version authoritative. The
# upstream-supported variable is harmless when Antigravity is not installed.
export AGY_CLI_DISABLE_AUTO_UPDATE=true

# Prepend in order so ${_AL_HOME}/.npm-global/bin lands FIRST in the final
# PATH (a stray /usr/local/bin shim must lose to the user-owned binary).
# Case-prepend stacks LIFO: the LAST successful case-block prepends in front
# of everything, so we put .local/bin FIRST and .npm-global/bin SECOND.
# Case-guards prevent double-prepend on re-source (idempotency).
case ":\${PATH}:" in
  *:${_AL_HOME}/.local/bin:*) : ;;
  *) PATH="${_AL_HOME}/.local/bin:\${PATH}" ;;
esac
case ":\${PATH}:" in
  *:${_AL_HOME}/.npm-global/bin:*) : ;;
  *) PATH="${_AL_HOME}/.npm-global/bin:\${PATH}" ;;
esac
export PATH
PROFILE
log_info "wrote /etc/profile.d/agentlinux.sh"

# Artefact 2: <home>/.bashrc marker block at TOP — non-interactive SSH
# (`ssh user@host 'cmd'`) + `sudo -u <user> bash -c 'cmd'`.
# The Ubuntu skel .bashrc early-returns for non-interactive shells
# (`case $- in *i*) ;; *) return;; esac`); --top placement puts our
# guard-source BEFORE that return so those invocations still pick up PATH +
# locale. Create an empty user-owned file first if .bashrc is absent (minimal
# container with no skel copy) so ensure_marker_block has a target.
if [[ ! -f "${_AL_HOME}/.bashrc" ]]; then
  install -m 0644 -o "$_AL_USER" -g "$_AL_USER" /dev/null "${_AL_HOME}/.bashrc"
fi
ensure_marker_block "${_AL_HOME}/.bashrc" "agentlinux-path" --top <<'BASHRC'
# AgentLinux PATH guard — sources /etc/profile.d/agentlinux.sh unconditionally
# so non-interactive bash invocations (ssh host 'cmd', sudo -u <user> bash -c)
# see the correct PATH + locale BEFORE the skel .bashrc case-return guard.
if [ -f /etc/profile.d/agentlinux.sh ]; then
  . /etc/profile.d/agentlinux.sh
fi
BASHRC
# ensure_marker_block leaves the file root-owned; re-assert <user>:<user> + 0644
# so the user can edit outside the block.
chown "${_AL_USER}:${_AL_USER}" "${_AL_HOME}/.bashrc"
chmod 0644 "${_AL_HOME}/.bashrc"
log_info "wrote agentlinux-path marker block to ${_AL_HOME}/.bashrc (--top)"

# Artefact 3: /etc/agentlinux.env — systemd EnvironmentFile (BHV-04), RT-02 +
# RT-04. FORMAT: literal KEY=VALUE, no `export`, no shell expansion (systemd and
# cron parse this shape literally; `PATH=$PATH:...` would store the literal
# string). NPM_CONFIG_PREFIX is the belt-and-braces fallback so consumers see
# the prefix even if <home>/.npmrc regresses; keep its value byte-identical to
# the .npmrc prefix line written by 30-nodejs.sh (a cross-grep enforces this).
# AGENTLINUX_USER + AGENTLINUX_AGENT_HOME are the runtime source-of-truth the
# catalog CLI reads (guard + dispatchRecipe user) — Task 6.
write_file_atomic 0644 /etc/agentlinux.env <<ENVFILE
PATH=${_AL_HOME}/.npm-global/bin:${_AL_HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin
NPM_CONFIG_PREFIX=${_AL_HOME}/.npm-global
AGENTLINUX_USER=${_AL_USER}
AGENTLINUX_AGENT_HOME=${_AL_HOME}
LANG=C.UTF-8
LC_ALL=C.UTF-8
AGY_CLI_DISABLE_AUTO_UPDATE=true
ENVFILE
log_info "wrote /etc/agentlinux.env (systemd EnvironmentFile + cron header template)"

# Artefact 4: /etc/cron.d/agentlinux — cron PATH header (BHV-03). The top-of-file
# `PATH=` applies to every job below. No default jobs ship. vixie-cron does NOT
# expand $PATH, so the literal PATH is written fully expanded; keep it
# byte-identical to /etc/agentlinux.env's PATH line (a cross-grep enforces this).
# The example-job comment names the install user in the user column.
write_file_atomic 0644 /etc/cron.d/agentlinux <<CRON
# AgentLinux cron environment (generated by agentlinux-install).
# Any cron job placed in this file inherits the PATH/locale below.
# Phase 2 ships NO default jobs. Example shape (do NOT uncomment):
#   0 3 * * * ${_AL_USER} /usr/bin/true

PATH=${_AL_HOME}/.npm-global/bin:${_AL_HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin
LANG=C.UTF-8
LC_ALL=C.UTF-8
AGY_CLI_DISABLE_AUTO_UPDATE=true
CRON
log_info "wrote /etc/cron.d/agentlinux (PATH + locale header; no default jobs)"

log_info "40-path-wiring: done (four artefacts written)"
