#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# plugin/provisioner/40-path-wiring.sh — six-mode PATH/locale wiring.
#
# Sourced by plugin/bin/agentlinux-install. Inherits `set -euo pipefail`, the
# ERR trap, and the tee redirect to /var/log/agentlinux-install.log from the
# entrypoint; this fragment therefore MUST NOT set its own strict-mode flags.
#
# Requirements satisfied:
#   BHV-02 — non-interactive SSH (`ssh agent@host '<cmd>'`)
#   BHV-03 — cron (`/etc/cron.d/agentlinux` PATH header)
#   BHV-04 — systemd `User=agent` (`EnvironmentFile=/etc/agentlinux.env`)
#   BHV-05 — `sudo -u agent [-i]` (profile.d for -i; .bashrc for bash -c)
#   BHV-06 — interactive bash login (/etc/profile → /etc/profile.d/*.sh)
#   RT-02  — /home/agent/.npm-global/bin is on PATH in every invocation mode
#   RT-04  — NPM_CONFIG_PREFIX env var (belt-and-braces for Pitfall 5)
#
# Four artefacts cover all six invocation modes (02-RESEARCH §Pattern 4):
#   1. /etc/profile.d/agentlinux.sh  (0644 root:root)  — BHV-05 -i + BHV-06
#   2. /home/agent/.bashrc TOP block (0644 agent:agent) — BHV-02 + BHV-05 bash -c
#   3. /etc/agentlinux.env           (0644 root:root)  — BHV-04
#   4. /etc/cron.d/agentlinux        (0644 root:root)  — BHV-03
#
# Path ordering: agent-owned prefixes FIRST, system prefixes last. Only paths
# under /home/agent are agent-owned; /usr/local/bin is root-owned standard.
# This prevents T-02-08 path-injection by a wider-writable directory earlier
# in PATH. Phase 3 extended this file: /home/agent/.npm-global/bin is
# prepended in all three literal-PATH artefacts (profile.d case-stack,
# agentlinux.env, cron.d); NPM_CONFIG_PREFIX (value: /home/agent/.npm-global)
# ships in agentlinux.env as a belt-and-braces Pitfall 5 mitigation (env-var
# precedence over .npmrc per npm docs, ensures systemd EnvironmentFile
# consumers see the prefix even if ~agent/.npmrc read regresses).
#
# Invariants enforced by this file (the plan's acceptance greps cross-verify
# the forbidden substrings literally do not appear anywhere in this source):
#   - State mutation routes through `write_file_atomic <mode> <dest> <<EOF`
#     (installer-owned full-file writes — same atomic-rename semantics as
#     `install -m <mode> /dev/stdin <dest>`, but portable to uutils-coreutils
#     on Ubuntu 26.04) or `ensure_marker_block` (partial edit on user-owned
#     ~agent/.bashrc). No raw-append or in-place editing.
#   - Zero privilege-escalation configuration shipped: Phase 2 locks the
#     no-default-drop-in rule; future phases use visudo_validate + 0440.
#   - Zero wrapper shim pointing at an agent-owned binary from a root-owned
#     bin directory (DOC-02 canonical anti-pattern — the exact class of bug
#     that breaks Claude Code self-update).
#   - Installer does not execute the profile.d fragment during install
#     (would pollute root's environment). It is written once, read later
#     by the login shells that source /etc/profile.

log_info "40-path-wiring: starting"

# Ensure /home/agent/.local/bin exists so the PATH prefix written below is not
# a dangling reference before the user ever writes a binary there. ensure_dir
# re-asserts mode+ownership on re-run to correct any out-of-band drift.
ensure_dir /home/agent/.local 0755 agent:agent
ensure_dir /home/agent/.local/bin 0755 agent:agent

# ---------------------------------------------------------------
# Artefact 1: /etc/profile.d/agentlinux.sh
# BHV-06 (interactive login) + BHV-05 (`sudo -u agent -i` login variant).
# Sourced by /etc/profile on login shells. Re-source guard prevents double
# PATH-prepend if the file is sourced twice in the same shell session
# (T-02-09 mitigation + INST-02 idempotency contract).
# `write_file_atomic` is the portable analogue of
# `install -m 0644 /dev/stdin <dest>` — same atomic-rename semantics, but
# routed through a same-directory tmpfile so it works on uutils-coreutils 0.7.0
# (the Rust `install` shipped on Ubuntu 26.04). uutils' install recursively
# readlink-chases /dev/stdin → /proc/self/fd/0 → "pipe:[NNN]" and ENOENTs
# whenever the destination already exists; the first run succeeds, the
# idempotent re-run fails. See plugin/lib/idempotency.sh `write_file_atomic`
# header for the full strace trail. The single-quoted heredoc tag keeps `$PATH`
# etc. literal in the written file.
# ---------------------------------------------------------------
write_file_atomic 0644 /etc/profile.d/agentlinux.sh <<'PROFILE'
# AgentLinux login environment (generated by agentlinux-install).
# Sourced by /etc/profile on interactive login shells AND `sudo -u agent -i`.
# Re-source guard: bails on second source in the same shell session so that
# rc reload (e.g. `exec bash -l`) does not double-prepend PATH entries.
[ -n "${AGENTLINUX_PROFILE_SOURCED:-}" ] && return
export AGENTLINUX_PROFILE_SOURCED=1

export LANG="${LANG:-C.UTF-8}"
export LC_ALL="${LC_ALL:-C.UTF-8}"

# Prepend in order so /home/agent/.npm-global/bin lands FIRST in the final
# PATH (Pitfall 4 — a stray /usr/local/bin shim must lose to the agent-owned
# binary). Case-prepend stacks LIFO: the LAST successful case-block prepends
# in front of everything, so we put .local/bin FIRST and .npm-global/bin
# SECOND. Case-guards prevent double-prepend on re-source (INST-02
# idempotency). Phase 3 RT-02 + RT-04.
case ":${PATH}:" in
  *:/home/agent/.local/bin:*) : ;;
  *) PATH="/home/agent/.local/bin:${PATH}" ;;
esac
case ":${PATH}:" in
  *:/home/agent/.npm-global/bin:*) : ;;
  *) PATH="/home/agent/.npm-global/bin:${PATH}" ;;
esac
export PATH
PROFILE
log_info "wrote /etc/profile.d/agentlinux.sh"

# ---------------------------------------------------------------
# Artefact 2: /home/agent/.bashrc marker block at TOP.
# BHV-02 (non-interactive SSH: `ssh agent@host 'cmd'`) + BHV-05 non-login
# (`sudo -u agent bash -c 'cmd'`).
#
# Pitfall 2 (02-RESEARCH): the Ubuntu skel /etc/skel/.bashrc starts with
#   case $- in *i*) ;; *) return;; esac
# which early-returns for non-interactive shells. An agentlinux block placed
# AFTER that guard would never run under `ssh host 'cmd'` or `sudo -u agent
# bash -c 'cmd'`. Our --top placement puts the guard-source BEFORE the skel
# early-return so non-interactive bash invocations pick up PATH + locale.
#
# If /home/agent/.bashrc doesn't exist (no skel copied — e.g., agent user
# created in a minimal container), create an empty agent-owned file so
# ensure_marker_block has a target. `install /dev/null` is atomic and sets
# mode + ownership at creation time.
# ---------------------------------------------------------------
if [[ ! -f /home/agent/.bashrc ]]; then
  install -m 0644 -o agent -g agent /dev/null /home/agent/.bashrc
fi
ensure_marker_block /home/agent/.bashrc "agentlinux-path" --top <<'BASHRC'
# AgentLinux PATH guard — sources /etc/profile.d/agentlinux.sh unconditionally
# so non-interactive bash invocations (ssh host 'cmd', sudo -u agent bash -c)
# see the correct PATH + locale BEFORE the skel .bashrc case-return guard.
if [ -f /etc/profile.d/agentlinux.sh ]; then
  . /etc/profile.d/agentlinux.sh
fi
BASHRC
# ensure_marker_block uses `install -m 0644` which leaves the file root-owned;
# re-assert agent:agent ownership so the user can edit outside the block on
# subsequent runs, and enforce 0644 to correct any out-of-band chmod drift.
chown agent:agent /home/agent/.bashrc
chmod 0644 /home/agent/.bashrc
log_info "wrote agentlinux-path marker block to /home/agent/.bashrc (--top)"

# ---------------------------------------------------------------
# Artefact 3: /etc/agentlinux.env
# BHV-04 (systemd `User=agent` units via `EnvironmentFile=/etc/agentlinux.env`).
# RT-02 + RT-04 (npm-global/bin prepend + NPM_CONFIG_PREFIX).
# FORMAT: literal `KEY=VALUE` lines, NO `export`, NO shell expansion. Both
# systemd EnvironmentFile and cron parse this shape literally (Pitfall 4);
# `PATH=$PATH:...` would store the literal string `$PATH:...` — never a
# runtime expansion. Fully-expanded literal PATH is the only correct form.
# NPM_CONFIG_PREFIX is the belt-and-braces fallback (Pitfall 5): systemd
# EnvironmentFile= consumers see the prefix even if ~agent/.npmrc read
# regresses. T-03-03 mitigation: value MUST be byte-identical to the prefix
# line in ~agent/.npmrc written by 30-nodejs.sh (/home/agent/.npm-global) —
# split-brain avoidance; a future accidental divergence fails the plan's
# cross-grep acceptance criterion.
# ---------------------------------------------------------------
write_file_atomic 0644 /etc/agentlinux.env <<'ENVFILE'
PATH=/home/agent/.npm-global/bin:/home/agent/.local/bin:/usr/local/bin:/usr/bin:/bin
NPM_CONFIG_PREFIX=/home/agent/.npm-global
LANG=C.UTF-8
LC_ALL=C.UTF-8
ENVFILE
log_info "wrote /etc/agentlinux.env (systemd EnvironmentFile + cron header template)"

# ---------------------------------------------------------------
# Artefact 4: /etc/cron.d/agentlinux
# BHV-03 (cron). The `PATH=` line at the top of a cron.d file applies to every
# job below it. Phase 2 ships NO default jobs — this file is the PATH contract
# future agent cron jobs inherit. Pitfall 4: classical vixie-cron does NOT
# expand `$PATH`, so the literal PATH is written author-time-expanded. Keep
# this PATH byte-identical to /etc/agentlinux.env — the plan's acceptance
# criterion cross-greps both for the same literal string.
# ---------------------------------------------------------------
write_file_atomic 0644 /etc/cron.d/agentlinux <<'CRON'
# AgentLinux cron environment (generated by agentlinux-install).
# Any agent cron job placed in this file inherits the PATH/locale below.
# Phase 2 ships NO default jobs. Example shape (do NOT uncomment):
#   0 3 * * * agent /usr/bin/true

PATH=/home/agent/.npm-global/bin:/home/agent/.local/bin:/usr/local/bin:/usr/bin:/bin
LANG=C.UTF-8
LC_ALL=C.UTF-8
CRON
log_info "wrote /etc/cron.d/agentlinux (PATH + locale header; no default jobs)"

log_info "40-path-wiring: done (four artefacts written)"
